Bug/73678 npm ls fails
Orckestra/orc-scripts pull request #1165
Opened 2023-09-19 16:15 UTC by jjghali

2023-10-11 15:46 UTC, orck-adrouin requested changes

2023-10-11 15:46 UTC, orck-adrouin commented on package-lock.json
which node version was used to generate this file?

2023-10-12 12:52 UTC, jjghali commented on package-lock.json
15.14 was used since it was the same version used in the pipeline

2023-10-16 17:16 UTC, orck-adrouin commented on package-lock.json
Can you delete the file and generate a new package-lock.json file using node 18 ? We'll migrate our reacts apps (orc-scripts, orc-shared, oms, analytics, settings) to node18 unless @joclefrancois disagree.

2023-10-16 17:36 UTC, jjghali commented on package-lock.json
It is done. Let me know if there are any issues

2023-10-17 15:40 UTC, orck-adrouin commented on .npmrc
>  package-lock=false
can you remove the `package-lock=false` line?

2023-12-08 15:22 UTC, closed without merging